### ISSUE TITLE
[Quick-XML] Upgrade to `0.38.0` and beyond

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [OpenSpeleo/openspeleo_core#25]
Ariane uses `string encoded` XML inside XML files.

It tends to completely confuse `Quick-XML`. I found a way to do it with `0.37.X`, but in `0.38` they changed the way unescaping works and I cant manage to find how to make it work anymore.

See comment: https://github.com/OpenSpeleo/openspeleo_core/blob/a7a3235bd380eb110d66e587d1f5bbc204a68b23/Cargo.toml#L15

I did manage to "sort of find a way", but it seems convoluted & slower than just using `0.37` => https://github.com/OpenSpeleo/openspeleo_core/blob/quick-xml-0.38/src_rust/ariane/deserialize.rs 

## Reproduce

```rust
use quick_xml::{Reader, events::Event};

fn parse_xml_like_xmltodict(xml: &str) -> String {
    let mut reader = Reader::from_str(xml);
    let mut buf = Vec::new();
    
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Text(e)) => {
                // This worked in 0.37.5
                let text = e.unescape().unwrap_or_default().to_string();
                return text;
            }
            Ok(Event::Eof) => break,
            _ => {}
        }
        buf.clear();
    }
    String::new()
}

// Test with escaped XML content
let xml = r#"<TopLevel>&lt;NestedA&gt;Object1&lt;/NestedA&gt;&lt;NestedB&gt;Object2&lt;/NestedB&gt;</TopLevel>"#;
let result = parse_xml_like_xmltodict(xml);
```

### Expected Result (and what we got in 0.37.5)

```
"<NestedA>Object1</NestedA><NestedB>Object2</NestedB>"
```

This matches exactly what Python's `xmltodict.parse()` produces for the same XML.

### Compilation Error

```rust
error[E0599]: no method named `unescape` found for struct `BytesText<'_>` in the current scope
  --> src/lib.rs:XX:XX
   |
XX |                 let text = e.unescape().unwrap_or_default().to_string();
   |                              ^^^^^^^^^ method not found in `BytesText<'_>`
```

### Attempted Workaround and Its Problems

When trying to use the new API:

```rust
use quick_xml::escape;

// Attempted fix
let raw_text = std::str::from_utf8(e.as_ref()).unwrap_or("");
let text = escape::unescape(raw_text)
    .map(|cow| cow.into_owned())
    .unwrap_or_else(|_| raw_text.to_string());
```

### Actual Result with 0.38.0

The parser now automatically unescapes during parsing and generates **multiple separate text events**:

1. `"NestedA"` 
2. `"Object1"`
3. `"/NestedA"`
4. `"NestedB"`
5. `"Object2"`
6. `"/NestedB"`

This results in only the **last** text event being captured: `"/NestedB"`

Instead of the expected: `"<NestedA>Object1</NestedA><NestedB>Object2</NestedB>"`
